version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5433"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    command: -p 5433

  web:
    build: .
    container_name: fastapi-web
    command: bash -c "alembic upgrade head && uvicorn demo:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5433
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
